[package]
name = "bsa-gprime"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-htslib = "1.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
anyhow = "1.0"

[dev-dependencies]
approx = "0.5"
